#!/bin/bash

set -e

# Status Codes
SUCCESS=0
INVALID_ARGUMENT=22

# Directories
export BR2_EXTERNAL=$(pwd)
BUILDROOT_DIR="${BR2_EXTERNAL}/buildroot"

while getopts "hb:c" opt; do
        case $opt in
                h)
                        echo "Usage: $0 -b [config_name]"
                        echo "  -h                      Show help page"
                        echo "  -b [config_name]        Build specific config"
                        echo "  -c                      Clean build directory"
                        exit ${SUCCESS}
                        ;;
                b)
                        pushd ${BUILDROOT_DIR}
                        make ${OPTARG}
                        make
                        popd
                        exit ${SUCCESS}
                        ;;
                c)
                        pushd ${BUILDROOT_DIR}
                        make clean
                        popd
                        exit ${SUCCESS}
                        ;;
                \?)
                        exit ${INVALID_ARGUMENT}
        esac
done

shift $((OPTIND - 1))

